### ISSUE TITLE
[SOLVED] Unable to query docker version: Get https://192.168.99.100:2376/v1.15/version: x509: certificate is valid for 192.168.99.102, not 192.168.99.100

### ISSUE THREAD

**Issue by g0blin79** [sparkfabrik/sparkdock#14]
Hi to all.

at the end of the installation process, if i launched a `docker-machine ls` I had this:

```
NAME     ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
dinghy   *        virtualbox   Running   tcp://192.168.99.100:2376           Unknown   Unable to query docker version: Get https://192.168.99.100:2376/v1.15/version: x509: certificate is valid for 192.168.99.102, not 192.168.99.100
```
I solved in this way:

`$ docker-machine regenerate-certs dinghy`

I don't know if could be useful to add something like this into the README. I would leave notice of that.

BTW: What fu***ng piece of code!!

**Comment by tuxisma** [comment]
thanks a lot! It worked for me.

**Comment by rebepoi** [comment]
Worked for me too! Life saver!

**Comment by steevehook** [comment]
Thanks man. really weird. Happened to me after I rebooted my machine

**Comment by liuqiqi1** [comment]
iptables

**Comment by dev120285** [comment]
While working with GIT Bash I had to regenerate ,once I switched back to Power Shell same effort was required.
docker-machine regenerate-certs myvm1

**Comment by chinmay90kulkarni** [comment]
Worked for me as well.. thanks

**Comment by liuweiming1997** [comment]
I am so sad because it not work for me, it still
sunday                generic   Timeout

by

➜  ~ docker-machine regenerate-certs sunday
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

**Comment by dev120285** [comment]
Try with --force param

**Comment by liujunberg** [comment]
It does work to me, thanks

**Comment by iplanetcn** [comment]
This works for me, thank you.
But it produces a new question, the docker-machine's IP address changed. Is there a good way?

**Comment by keenkit** [comment]
Works for me as well, thanks!

**Comment by lmbautista** [comment]
EC2 working again! Thanks!!! 🤓

**Comment by pdsiaj** [comment]
it didn't work for me, despite using force at the end, what other way can we try to rectify this please

**Comment by remycerigny** [comment]
Work for me too ! Thanks a lot mate :)

**Comment by ismbabuIBM** [comment]
Works for me as well.. Thanks!

**Comment by AbilioSouza** [comment]
thanks, it works for me

**Comment by archVille** [comment]
> Hi to all.
> 
> at the end of the installation process, if i launched a `docker-machine ls` I had this:
> 
> ```
> NAME     ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
> dinghy   *        virtualbox   Running   tcp://192.168.99.100:2376           Unknown   Unable to query docker version: Get https://192.168.99.100:2376/v1.15/version: x509: certificate is valid for 192.168.99.102, not 192.168.99.100
> ```
> 
> I solved in this way:
> 
> `$ docker-machine regenerate-certs dinghy`
> 
> I don't know if could be useful to add something like this into the README. I would leave notice of that.
> 
> BTW: What fu***ng piece of code!!

worked for me too. Nice!

**Comment by charlesgres** [comment]
You may need to add the -client-certs option:

`docker-machine regenerate-certs --client-certs dinghy`

**Comment by ThatcherT** [comment]
Worked for me!
