### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Mithenks** [sparkfabrik/sparkdock#15]
Hello,
in the Readme.md, the link "https://github.com/sparkfabrik/sparkdock/blob/master/config/osx/dnsmasq.conf" must be "https://github.com/sparkfabrik/sparkdock/blob/master/config/macosx/dnsmasq.conf".

Regards,
  Michele

**Comment by stickgrinder** [comment]
Thanks for your feedback, I'm going to fix it.
