### ISSUE TITLE
Ubuntu install fails due to port conflict

### ISSUE THREAD

**Issue by Pinolo** [sparkfabrik/sparkdock#8]
Tested on Ubuntu 14 LTS. When running the install script, the activation of the dnsdock container fails with this error:

`Error response from daemon: driver failed programming external connectivity on endpoint dnsdock (880da53b9f12d7f6e80e68f50e11b881dbce852054d15dd91238ad5bc5b44998): Error starting userland proxy: listen udp 172.17.0.1:53: bind: address already in use.`

Turns out dnsmasq, already listening on port 53, is causing this error. The current workaround consists in stopping the dnsmasq service, manually starting the dnsdock container, starting the dnsmasq service.

Also, once you have done those steps, you can't just relaunch the install script, because it tries to recreate the dnsdock container, not checking it's already running.

**Comment by paolomainardi** [comment]
Thanks for reporting the bugs.

For the last point I suggest (as we do for OSX) to do a 'docker rm -vf dnsdock || true' as the first step to install dnsdock.

**Comment by paolomainardi** [comment]
@stickgrinder

**Comment by Pinolo** [comment]
#9
